### ISSUE TITLE
Remove nginx proxy

### ISSUE THREAD

**Issue by MatMoore** [alphagov/search-api#1110]
From: https://trello.com/c/c7BU3pYT/9-remove-elasticsearch-local-proxy-upstream

# What

On our rummager servers, we have an Nginx instance that load balances between the 3 elasticsearch nodes.

https://github.com/alphagov/govuk-puppet/blob/ca95508742d1417449ec1c872de0ef26a71fc6c3/modules/govuk_elasticsearch/manifests/local_proxy.pp

We can remove this and set up a connection strategy in the
 [elasticsearch client](http://www.rubydoc.info/gems/elasticsearch-transport) used by rummager.

The nginx server configuration can be found at `search-1.api.integration:/etc/nginx/sites-available/elasticsearch-local-proxy`

```
upstream elasticsearch-local-proxy-upstream {
  server api-elasticsearch-1.api:9200 max_fails=3 fail_timeout=10s;
  server api-elasticsearch-2.api:9200 max_fails=3 fail_timeout=10s;
  server api-elasticsearch-3.api:9200 max_fails=3 fail_timeout=10s;
}

server {
  listen localhost:9200;

  # Needed to do keepalives upstream
  proxy_http_version 1.1;

  # Try next upstream if one returns an error
  proxy_next_upstream error timeout http_500 http_502 http_503 http_504;

  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-Server $host;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_redirect off;

  proxy_connect_timeout 1s;
  proxy_read_timeout 60;

  # Don't restrict the size of queries or documents.
  client_max_body_size 4g;

  access_log /var/log/nginx/elasticsearch-local-proxy-access.log timed_combined;
  access_log /var/log/nginx/elasticsearch-local-proxy-json.event.access.log json_event;
  error_log /var/log/nginx/elasticsearch-local-proxy-error.log;

  location / {
    # Only accept connnections over loopback.
    allow 127.0.0.1;
    deny all;

    proxy_pass http://elasticsearch-local-proxy-upstream;
  }
}
```

# Why

Since rummager is now using the ruby [elasticsearch client](http://www.rubydoc.info/gems/elasticsearch-transport), it can handle failures and load balancing itself. This makes our nginx proxy is redundant, and we can probably handle failures better without it in the way.

**Comment by barrucadu** [comment]
Solved by not running our own Elasticsearch
