### ISSUE TITLE
What version of Elasticsearch are you running now?

### ISSUE THREAD

**Issue by pezholio** [alphagov/search-api#507]
We're currently working on [getting our fork up to date with yours](https://github.com/theodi/rummager/pull/18), and I'm encountering all sorts of oddness on Elasticsearch 1.4.0 and 1.4.5. What Elasticsearch version is Rummager now known to work with?

**Comment by rboulton** [comment]
We're currently running 1.4.4, and 1.4.5 in some environments.

**Comment by pezholio** [comment]
Cool, thanks!
