### ISSUE TITLE
Is there any way to get the CSV files that match a search? 

### ISSUE THREAD

**Issue by georgiana-b** [alphagov/search-api#631]
Hello! Is there any way to get the CSV files whose title matches a search query instead of their parent HTML documents?  I looked over the code and I assume the answer is 'no' but I might have missed something.

**Comment by tijmenb** [comment]
Hi Georgiana - we don't currently have a way to export CSV files directly (we have internal tools to do that). What data are you after?

**Comment by georgiana-b** [comment]
I would like all the CSV or XLS(X) files for transactions over £25000.

**Comment by tijmenb** [comment]
Rummager is the search API for gov.uk (used https://www.gov.uk/search). It only contains pages that are on the website. Perhaps you are looking for a different data source?

**Comment by georgiana-b** [comment]
I was vague so I'll give an example. [This request](https://www.gov.uk/search?q=25k) returns several results among which [this HTML page](https://www.gov.uk/government/publications/transactions-over-25k-2012-2013).I'm wondering if I could get directly the CSV on that  HTML page, if it is indexed separately.

**Comment by georgiana-b** [comment]
I should mention that I retrieved some of these tabular files from [data.gov.uk](https://data.gov.uk/).  Are all these downloads available there?

**Comment by tijmenb** [comment]
We currently don't store attached documents (like the CSV you're pointing to) in our search index. So I think you will have to find it via the page itself.

**Comment by georgiana-b** [comment]
I see. Thank you!
